/* testing */

export const lighthouseUrls = {
	Home: '/',
	Guides: '/guides/app',
	Methodology: '/methodology/dataProcessing',
	Explorer_category_geo: '/explorer/category/geo/hp_feature_design?categsGeoSortBy=total&categsStreamgraphsSorting=off&categsTimeGraph=trends&filters=(installerRegionNames:!(),installerRegionType:country21,propertyRegionNames:!(),propertyRegionType:country21)&interval=1y&numTimeGraph=percentiles&regionType=itl21_3&regionTypes=!(country21,itl21_1,itl21_2,itl21_3,lad21)&stackedBarsExtents=absolute&stringsGeoSortBy=total&stringsStreamgraphsSorting=off&stringsTimeGraph=trends&stringsTopCount=10&trendType=cumulative&viewId=',
	Explorer_category_stats: '/explorer/category/stats/hp_feature_design?categsGeoSortBy=total&categsStreamgraphsSorting=off&categsTimeGraph=trends&filters=(installerRegionNames:!(),installerRegionType:country21,propertyRegionNames:!(),propertyRegionType:country21)&interval=1y&numTimeGraph=percentiles&regionType=itl21_3&regionTypes=!(country21,itl21_1,itl21_2,itl21_3,lad21)&stackedBarsExtents=absolute&stringsGeoSortBy=total&stringsStreamgraphsSorting=off&stringsTimeGraph=trends&stringsTopCount=10&trendType=cumulative&viewId=',
	Explorer_category_time: '/explorer/category/time/hp_feature_design?categsGeoSortBy=total&categsStreamgraphsSorting=off&categsTimeGraph=trends&filters=(installerRegionNames:!(),installerRegionType:country21,propertyRegionNames:!(),propertyRegionType:country21)&interval=1y&numTimeGraph=percentiles&regionType=itl21_3&regionTypes=!(country21,itl21_1,itl21_2,itl21_3,lad21)&stackedBarsExtents=absolute&stringsGeoSortBy=total&stringsStreamgraphsSorting=off&stringsTimeGraph=trends&stringsTopCount=10&trendType=cumulative&viewId=',
	Explorer_category_time_streams: '/explorer/category/time/hp_feature_design?categsGeoSortBy=total&categsStreamgraphsSorting=off&categsTimeGraph=streams&filters=(installerRegionNames:!(),installerRegionType:country21,propertyRegionNames:!(),propertyRegionType:country21)&interval=1y&numTimeGraph=percentiles&regionType=itl21_3&regionTypes=!(country21,itl21_1,itl21_2,itl21_3,lad21)&stackedBarsExtents=absolute&stringsGeoSortBy=total&stringsStreamgraphsSorting=off&stringsTimeGraph=trends&stringsTopCount=10&trendType=cumulative&viewId=',
	Explorer_count_geo: '/explorer/count/geo/installations?categsGeoSortBy=total&categsStreamgraphsSorting=off&categsTimeGraph=trends&filters=(installerRegionNames:!(),installerRegionType:country21,propertyRegionNames:!(),propertyRegionType:country21)&interval=1y&numTimeGraph=percentiles&regionType=country21&regionTypes=!(country21,itl21_1,itl21_2,itl21_3,lad21)&stackedBarsExtents=absolute&stringsGeoSortBy=total&stringsStreamgraphsSorting=off&stringsTimeGraph=trends&stringsTopCount=10&trendType=progressive&viewId=',
	Explorer_count_stats: '/explorer/count/stats/installations?categsGeoSortBy=total&categsStreamgraphsSorting=off&categsTimeGraph=trends&filters=(installerRegionNames:!(),installerRegionType:country21,propertyRegionNames:!(),propertyRegionType:country21)&interval=1y&numTimeGraph=percentiles&regionType=itl21_3&regionTypes=!(country21,itl21_1,itl21_2,itl21_3,lad21)&stackedBarsExtents=absolute&stringsGeoSortBy=total&stringsStreamgraphsSorting=off&stringsTimeGraph=trends&stringsTopCount=10&trendType=progressive&viewId=',
	Explorer_count_time: '/explorer/count/time/installations?categsGeoSortBy=total&categsStreamgraphsSorting=off&categsTimeGraph=trends&filters=(installerRegionNames:!(),installerRegionType:country21,propertyRegionNames:!(),propertyRegionType:country21)&interval=1y&numTimeGraph=percentiles&regionType=itl21_3&regionTypes=!(country21,itl21_1,itl21_2,itl21_3,lad21)&stackedBarsExtents=absolute&stringsGeoSortBy=total&stringsStreamgraphsSorting=off&stringsTimeGraph=trends&stringsTopCount=10&trendType=progressive&viewId=',
	Explorer_number_geo: '/explorer/number/geo/installation_cost?categsGeoSortBy=total&categsStreamgraphsSorting=off&categsTimeGraph=trends&filters=(installerRegionNames:!(),installerRegionType:country21,propertyRegionNames:!(),propertyRegionType:country21)&interval=1y&numTimeGraph=percentiles&regionType=itl21_3&regionTypes=!(country21,itl21_1,itl21_2,itl21_3,lad21)&stackedBarsExtents=absolute&stringsGeoSortBy=total&stringsStreamgraphsSorting=off&stringsTimeGraph=trends&stringsTopCount=10&trendType=cumulative&viewId=',
	Explorer_number_stats: '/explorer/number/stats/installation_cost?categsGeoSortBy=total&categsStreamgraphsSorting=off&categsTimeGraph=trends&filters=(installerRegionNames:!(),installerRegionType:country21,propertyRegionNames:!(),propertyRegionType:country21)&interval=1y&numTimeGraph=percentiles&regionType=itl21_3&regionTypes=!(country21,itl21_1,itl21_2,itl21_3,lad21)&stackedBarsExtents=absolute&stringsGeoSortBy=total&stringsStreamgraphsSorting=off&stringsTimeGraph=trends&stringsTopCount=10&trendType=cumulative&viewId=',
	Explorer_number_time: '/explorer/number/time/installation_cost?categsGeoSortBy=total&categsStreamgraphsSorting=off&categsTimeGraph=trends&filters=(installerRegionNames:!(),installerRegionType:country21,propertyRegionNames:!(),propertyRegionType:country21)&interval=1y&numTimeGraph=percentiles&regionType=itl21_3&regionTypes=!(country21,itl21_1,itl21_2,itl21_3,lad21)&stackedBarsExtents=absolute&stringsGeoSortBy=total&stringsStreamgraphsSorting=off&stringsTimeGraph=trends&stringsTopCount=10&trendType=cumulative&viewId=',
	Explorer_string_geo: '/explorer/string/geo/hp_id_brand?categsGeoSortBy=total&categsStreamgraphsSorting=off&categsTimeGraph=trends&filters=(installerRegionNames:!(),installerRegionType:country21,propertyRegionNames:!(),propertyRegionType:country21)&interval=1y&numTimeGraph=percentiles&regionType=itl21_3&regionTypes=!(country21,itl21_1,itl21_2,itl21_3,lad21)&stackedBarsExtents=absolute&stringsGeoSortBy=total&stringsStreamgraphsSorting=off&stringsTimeGraph=trends&stringsTopCount=10&trendType=cumulative&viewId=',
	Explorer_string_stats: '/explorer/string/stats/hp_id_brand?categsGeoSortBy=total&categsStreamgraphsSorting=off&categsTimeGraph=trends&filters=(installerRegionNames:!(),installerRegionType:country21,propertyRegionNames:!(),propertyRegionType:country21)&interval=1y&numTimeGraph=percentiles&regionType=itl21_3&regionTypes=!(country21,itl21_1,itl21_2,itl21_3,lad21)&stackedBarsExtents=absolute&stringsGeoSortBy=total&stringsStreamgraphsSorting=off&stringsTimeGraph=trends&stringsTopCount=10&trendType=cumulative&viewId=',
	Explorer_string_time: '/explorer/string/time/hp_id_brand?categsGeoSortBy=total&categsStreamgraphsSorting=off&categsTimeGraph=trends&filters=(installerRegionNames:!(),installerRegionType:country21,propertyRegionNames:!(),propertyRegionType:country21)&interval=1y&numTimeGraph=percentiles&regionType=itl21_3&regionTypes=!(country21,itl21_1,itl21_2,itl21_3,lad21)&stackedBarsExtents=absolute&stringsGeoSortBy=total&stringsStreamgraphsSorting=off&stringsTimeGraph=trends&stringsTopCount=10&trendType=cumulative&viewId=',
	Explorer_string_time_streams: '/explorer/string/time/hp_id_brand?categsGeoSortBy=total&categsStreamgraphsSorting=off&categsTimeGraph=trends&filters=(installerRegionNames:!(),installerRegionType:country21,propertyRegionNames:!(),propertyRegionType:country21)&interval=1y&numTimeGraph=percentiles&regionType=itl21_3&regionTypes=!(country21,itl21_1,itl21_2,itl21_3,lad21)&stackedBarsExtents=absolute&stringsGeoSortBy=total&stringsStreamgraphsSorting=off&stringsTimeGraph=trends&stringsTopCount=10&trendType=cumulative&viewId=',
};
